### ISSUE TITLE
Getting to Output Stage

### ISSUE THREAD

**Issue by Narobix** [microsoft/nmarc#4]
I found several errors before getting an output working from the code download.

1. Property ':Groups' not found
 - Updated AlignmentReport.cs groups and users to :Groups and :Users

2. Property 'approximate_messages_count' not found
 - Fixed messages_count to approximate_messages_count in Groups.cs

3.  Line 10 YAML - The string was not recognized as a valid DateTime
 - Never rather than date statement that could be fixed by the same coding as your lastaccessed.
 - I just copied another date to quickly get past this.

4. Expected 'StreamEnd', got 'DocumentStart'
 - YAML file - removed the --- from between groups and user sections 

5. Property 'community_message_count' not found
 - Fixed public_message_count to community_message_count in User.CS

I should mention I'm in Australia so not sure if some field names differ based on geolocation.
And this is where I encounter the issue you already have regarding group admin outputs.

**Comment by HenrikBernhard** [comment]
I'm also seeing a similar issue
It reports the below error when i click the "convert alignment report" 

Started conversion...

YamlDotNet.Core.YamlException: (Line: 2, Col: 1, Idx: 4) - (Line: 2, Col: 1, Idx: 4): Exception during deserialization ---> System.Runtime.Serialization.SerializationException: Property ':groups' not found on type 'NMARC.Models.AlignmentReport'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at NMARC.FrmNativeModeConc.ParseAlignmentReport(TextReader alignmentReportYaml) in C:\Users\hxb\Source\Repos\nmarc\src\WinFormsApp\MainWindow.cs:line 121
   at NMARC.FrmNativeModeConc.BtnConvert_Click(Object sender, EventArgs e) in C:\Users\hxb\Source\Repos\nmarc\src\WinFormsApp\MainWindow.cs:line 47Conversion error. Please report the messages listed above after removing any sensitive data.

**Comment by Narobix** [comment]
@HenrikBernhard  sorry if my previous was not clear enough but I was trying to be brief. If you search the files in the project one of the short ones potentially called ~alignment~ you will find one that determines it is trying to match just “groups” and just “users”
If you update those to include the “:” in front it rectifies those.

Same goes for updating the other items I list that make it fail.

Further to my previous  if owners are not a concern like they aren’t for me - a simple column value shift to the left in excel fixes the numbers to corrected column headers.

**Comment by HenrikBernhard** [comment]
@Narobix thanks for the explanation
I'm by no means a developer, but your clarification enabled me to fix the issues. Thanks!
Had to fix issues 1,2 & 4 from your list but not 3 & 5

**Comment by Narobix** [comment]
> @Narobix thanks for the explanation
> 
> I'm by no means a developer, but your clarification enabled me to fix the issues. Thanks!
> 
> Had to fix issues 1,2 & 4 from your list but not 3 & 5 
> 
> 

Yeah right - 3 line 10 represented my all company group but weirdly i ended up with 2 of them in output one defunct. and with 5 id be curious to know what geo location your tenancy is in?

**Comment by HenrikBernhard** [comment]
geo located in europe

**Comment by brianly** [comment]
@Narobix @HenrikBernhard This is a server-side bug that the product group are looking at. To workaround the issue you need to tweak some of the YAML to match what is output. I was going to make these changes, but got told to hang on.

**Comment by brianly** [comment]
I have a fix for the new format over at https://github.com/brianly/nmarc. Just waiting on a colleague to do a quick test of it. There are more changes than I expected:

- The YAML now contains multiple documents. I followed some of the YamlDotNet samples to handle this, but I feel like there is a cleaner way, but it works.
- There are a few changes to the YAML documents like `approximate_messages_count` since these numbers are constantly changing, and more minor tweaks like `Id` becaming `id`, etc. in a few places.
- With multiple documents being included, there are some additions currently not being handled like `GROUP_LEVEL_GUESTS`. Adding this soon.

**Comment by achaganti** [comment]
Receiving the below error after building and attempting to run the alignment tool 
Started conversion...

YAML file loaded and parsed.

System.NullReferenceException: Object reference not set to an instance of an object.
   at NMARC.FrmNativeModeConc.BtnConvert_Click(Object sender, EventArgs e) in C:\Users\wb370315\source\repos\nmarc\src\WinFormsApp\MainWindow.cs:line 55Conversion error. Please report the messages listed above after removing any sensitive data.

**Comment by brianly** [comment]
Closing this issue since multiple issues with updates to the format of the YAML have been made in the intervening period. If issues are still occurring opening a new bug is best. 

Feedback on how frustrating it is to have to deal with YAML has been provided to the team responsible for Native Mode. They would like to offer some improvements, but other priorities have taken their time.
